apiVersion: v1
kind: Secret
metadata:
  name: fiapdonatecampaign-secrets
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Server=sqlserver,1433;Database=FiapDonateDb;User Id=sa;Password=REPLACE_WITH_SQL_SERVER_PASSWORD;TrustServerCertificate=True;
  Jwt__Key: REPLACE_WITH_A_RANDOM_JWT_SIGNING_KEY_AT_LEAST_32_CHARACTERS
  RabbitMq__Password: REPLACE_WITH_RABBITMQ_PASSWORD